
GET http://localhost:8080/api/users HTTP/1.1

###
POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "danteBenitez",
    "email": "benitezdante123@gmail.com"
}

###
POST http://localhost:8080/api/publications HTTP/1.1
Content-Type: application/json

{
    "title": "Una nueva publicación - Parte V",
    "content": "asdad",
    "authorId": "6516fc12e5f61b712765c8d4"
}

###
GET http://localhost:8080/api/publications HTTP/1.1

